### ISSUE TITLE
Labels not in center of watch (07:10 in video)

### ISSUE THREAD

**Issue by coelle** [objcio/S01E193-analog-clock-part-2#1]
With Xcode Version 13.4.1 (13F100) the origin of the Labels is not in the center of the ticks but at the left top part of the screen. GeometryReader seems to be the culprit. If I remove it, the Labels look nice.

<img width="1051" alt="Without_GeometryReader" src="https://user-images.githubusercontent.com/3898865/180605939-4e2a8081-f203-4247-97f3-72f787162d29.png">

<img width="1051" alt="With_GeometryReader" src="https://user-images.githubusercontent.com/3898865/180605957-188d7d8e-8509-41af-bd4d-d056c695263d.png">

**Comment by chriseidhof** [comment]
Yes, IIRC `GeometryReader` now aligns everything top leading, but this wasn't always the same on every platform!

**Comment by coelle** [comment]
See my PR https://github.com/objcio/S01E193-analog-clock-part-2/pull/2
